def initialize():
    global TOTAL_DEMAND, LOW_COST, HIGH_COST, TOTAL_STAGES, NUM_ADV_HISTORY, LR, GAMMA, NUM_ACTIONS
    global ACTION_STEP, NUM_STOCHASTIC_ITER, NUM_EPISODES, NUM_EPISODES_RESET, EPISODE_ADV_INCREASE
    global REWARDS_DIVISION_CONST,REPLAY_BUFFER_SIZE,PROB_BREAK_LIMIT_LN,CONVERGE_BREAK, PRINT_STEP
    global BATCH_UPDATE_SIZE,BUFFER_PLAY_COEFFICIENT, NUM_PROCESS,NUM_TRACE_EQUILIBRIA
    global TIMESTEPS, NUM_TIMESTEPS,CON_ACTIONS_RANGE,NUM_MODEL_SAVE,MODELS_DIR,LOG_DIR

    TOTAL_DEMAND = 400
    LOW_COST = 57
    HIGH_COST = 71
    TOTAL_STAGES = 25
    NUM_ADV_HISTORY = 3
  
    LR = 0.00003
    GAMMA = 1
    NUM_ACTIONS = 20
    CON_ACTIONS_RANGE=60
    ACTION_STEP = 3
    NUM_STOCHASTIC_ITER = 3
    REWARDS_DIVISION_CONST = 1000

   
    NUM_EPISODES = 3_000_000
    EPISODE_ADV_INCREASE = 3_000_000
    # NUM_EPISODES = 3
    # EPISODE_ADV_INCREASE = 3
   
    NUM_EPISODES_RESET = NUM_EPISODES
    # INCREASE IN NUM OF EPISODES FOR EACH ADV IN SUPPORT
    
    NUM_PROCESS=30

    NUM_TRACE_EQUILIBRIA=1
    #HOW OFTEN THE MODEL SHOULD BE SAVED.
    NUM_MODEL_SAVE=3

    MODELS_DIR="models"
    LOG_DIR="logs"
    